# Maintainer: KV5d
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=i-bin
pkgver=0.1.0
pkgrel=1
pkgdesc="i is a program to instantly pull your public IP address circumventing the hassle to google such or run bloated like programs for when it is needed."
url="https://github.com/KV5d/i"
license=("MIT")
arch=("x86_64")
provides=("i")
conflicts=("i")
source=("https://github.com/KV5d/i/releases/download/v$pkgver/i-$pkgver-x86_64.tar.gz")
sha256sums=("2db483028128cc0f2d19bcbaefa7c676be4ed8e9cbda2a521d834031428e1355")

package() {
    install -Dm755 i -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
